name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Déclenche le déploiement sur les poussées vers la branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt

    - name: Run tests
      run: |
        pytest api/test_api.py  # Exécute les tests unitaires avec Pytest

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: customer-risk-profile
      run: |
        # Installer la CLI Heroku
        curl https://cli-assets.heroku.com/install.sh | sh
        
        # Connexion à Heroku avec la clé API
        echo "Authentification Heroku..."
        echo $HEROKU_API_KEY | heroku auth:token

        # Ajout du remote Heroku
        heroku git:remote --app $HEROKU_APP_NAME

        # Déploiement sur Heroku
        git config --global user.name "Gilgiltsu"
        git config user.email "telli.gilles@gmail.com"

        git add .
        git commit -m "Deploy from GitHub Actions" || echo "No changes to commit"
        
        echo "Pushing to Heroku..."
        git push heroku main || { echo "Deployment failed"; exit 1; }

        echo "Deployment successful!"
